import type { Metadata } from "next";

// Imports fonts from Google using Next.js font optimization.
import { Geist, Geist_Mono } from "next/font/google";

// Imports the Header component and ToastProvider for displaying notifications.
import Header from "@/src/components/ui/header";
import { ToastProvider } from "@/src/components/ui/use-toast";

// Imports global CSS styles.
import "./globals.css";

// Configures the Geist Sans font with a CSS variable and subset.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configures the Geist Mono font with a CSS variable and subset.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Defines page metadata such as title and description.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Exports the RootLayout component which wraps every page.
// It includes the Header, ToastProvider for notifications, and global styles.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-white`}
      >
        <Header />
        <ToastProvider>
          <div className="mt-24">{children}</div>
        </ToastProvider>
      </body>
    </html>
  );
}
